version: '3.7'
services:
  mysql-standalone:
    container_name: mysql-standalone
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=photo
    ports:
      - "3306:3306"
    networks:
      - application-network

  backend01:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: backend01
    ports:
      - '3001:8080'
    networks:
      - application-network
    depends_on:
      - mysql-standalone
      - redis-standalone
    environment:
      - DATABASE_HOST=mysql-standalone
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=photo
      - DATABASE_PORT=3306
      - REDIS_PORT=6379
      - REDIS_HOST=redis-standalone

  backend02:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: backend02
    ports:
      - '3002:8080'
    networks:
      - application-network
    depends_on:
      - mysql-standalone
      - redis-standalone
    environment:
      - DATABASE_HOST=mysql-standalone
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=photo
      - DATABASE_PORT=3306
      - REDIS_PORT=6379
      - REDIS_HOST=redis-standalone
  services:
    redis-standalone:
      container_name: redis-standalone
      image: redis
      ports:
        - "6379:6379"
      networks:
        - application-network

networks:
  application-network:
    driver: bridge
