spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
aws:
  s3:
    serverUrl: s3.sa-east-1.amazonaws.com
    accessKey: your access key
    secretKey: your secret key
    bucket: apiphoto-bucket
    region: sa-east-1

