spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  liquibase:
    enabled: false
aws:
  s3:
    serverUrl: s3.sa-east-1.amazonaws.com
    accessKey: your access key
    secretKey: your secret key
    bucket: apiphoto-bucket
    region: sa-east-1

config:
  jwt:
    secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE1ODk1MTUyODIsImV4cCI6MTYyMTA1MTI4MiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.MeIhSTbnrrd-s1jqkcSA3p3Slz4u-VZN7Gltr524LMw
    expiration: 86400000


