spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
aws:
  s3:
    serverUrl: s3.sa-east-1.amazonaws.com
    accessKey: your access key
    secretKey: your secret key
    bucket: apiphoto-bucket
    region: sa-east-1

