spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
aws:
  s3:
    serverUrl: s3.sa-east-1.amazonaws.com
    accessKey: your access key
    secretKey: your secret key
    bucket: apiphoto-bucket
    region: sa-east-1


